# Generated by Django 3.0.14 on 2024-05-14 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240514_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('SB', 'Shirts And Blouses'), ('TS', 'T-Shirts'), ('SK', 'Skirts')], max_length=2),
        ),
    ]
